### ISSUE TITLE
ドメイン取得

### ISSUE THREAD

**Issue by hitoshietoh** [exo2017/TESOFFICIAL#15]

**Comment by saltboy** [comment]
ドメイン取得完了しました。

■ドメイン登録完了通知■
───────────────────────────────────
ドメイン名..................：ex-sit.tokyo
───────────────────────────────────
お名前.comをご利用いただき、まことにありがとうございます。

上記ドメイン名のドメイン登録が完了した事をお知らせいたします。
以下の詳細をご確認ください。

**Comment by hitoshietoh** [comment]
ではドメイン連携お願いします。
https://github.com/exo2017/TESOFFICIAL/issues/16
