### ISSUE TITLE
ワイヤー作成

### ISSUE THREAD

**Issue by hitoshietoh** [exo2017/TESOFFICIAL#7]

**Comment by hitoshietoh** [comment]
ページ構成はこんな感じですかね

- TOP
- info
- about
- access

**Comment by hitoshietoh** [comment]
ページ構成はこうか！

- Top
- Info
- About
- Animals
- Shop（どっかのカートにリンク）

**Comment by saltboy** [comment]
ワイヤーは一旦終了します。
